#!/bin/bash
GIT_BASE_PATH=$(git rev-parse --show-toplevel)
FRONTEND_PATH="$GIT_BASE_PATH"/frontend
BACKEND_PATH="$GIT_BASE_PATH"/backend
FORMATTED_FILE_EXTENSIONS="java|ts|html|css|scss|xml|json|yml|yaml|mjs"

get_changed_files() {
    path=$1
    delimiter=${2:-' '}
    GIT_BASE_PATH=$(git rev-parse --show-toplevel)
    git diff --cached --name-only --diff-filter=d --line-prefix="$GIT_BASE_PATH"/ "$path" \
        | grep -E "\.($FORMATTED_FILE_EXTENSIONS)$" \
        | tr '\n' "$delimiter"
}

has_changed() {
    files=$1
    echo "$files" | grep -q .
}

frontend_files=$(get_changed_files "$FRONTEND_PATH" ' ')
backend_files=$(get_changed_files "$BACKEND_PATH" ' ')
backend_files_for_maven=$(get_changed_files "$BACKEND_PATH" ',')

echo "*****Running prettier******"
cd "$FRONTEND_PATH" || exit
if ! has_changed "$frontend_files"; then
  echo "No files found to format. Skipping."
else
  echo "Formatting changed frontend files..."
  npm run prettier:lint:format:specific $frontend_files || exit 1
fi
echo "*****Finish running prettier******"

echo "---------------------------------------------------------"

echo "*****Running eslint******"
cd "$FRONTEND_PATH" || exit
has_changed "$frontend_files"
if ! has_changed "$frontend_files"; then
  echo "No files found to format. Skipping."
else
  echo "Formatting changed frontend files..."
  npm run lint:format:specific $frontend_files || exit 1
fi

echo "*****Finish running eslint******"

echo "---------------------------------------------------------"

echo "*****Running maven formatter******"
cd "$BACKEND_PATH" || exit
has_changed "$backend_files_for_maven" && mvn -f pom.xml spotless:apply -DspotlessFiles="$backend_files_for_maven" || echo "No files found to format"
echo "*****Finish running maven formatter******"

echo "---------------------------------------------------------"

echo "*****Adding changes to git******"
cd "$GIT_BASE_PATH" || exit
has_changed "$frontend_files" && git add $frontend_files -v || echo "No frontend files changed, nothing to add"
has_changed "$backend_files" && git add $backend_files -v || echo "No backend files files changed, nothing to add"
echo "*****Formatted files added again******"

status=$?
exit $status
