---
extends: default

ignore: |
  node_modules
  frontend/node_modules/
  frontend/pnpm-lock.yaml
  pnpm-lock.yaml

rules:
  truthy:
    allowed-values: ['true', 'false', 'on']
  document-start:
    level: error
  line-length:
    max: 170
