sonar.java.binaries=**/target/classes
sonar.tests=frontend/src,backend/src/test
sonar.test.inclusions=**/*.spec.ts,**/*Test.java
sonar.sources=frontend/src,backend/src
sonar.exclusions=**/node_modules/**
sonar.coverage.exclusions=**/PctsApplication.java,**/SpringSecurityConfig.java,**/main.ts