sonar.projectKey=pcts
sonar.projectName=pcts

#For local usage only, on the pipeline the following server is used: https://sonar-githubactions.puzzle.ch
sonar.host.url=https://sonar.puzzle.ch

# Define all the multicriteria identifiers as a comma-separated list
sonar.issue.ignore.multicriteria=e1,e2,e3

# e1: Disables the rule which marks TODOs as issues
sonar.issue.ignore.multicriteria.e1.ruleKey=java:S1135
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.java

# e2: Disables only being able to have one 'break' or 'continue' statement per loop
sonar.issue.ignore.multicriteria.e2.ruleKey=java:S135
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.java

# e3: Disables the requirement of having a specific ordering of imports
sonar.issue.ignore.multicriteria.e3.ruleKey=java:S8445
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*.java

sonar.coverage.exclusions=\
  backend/src/test/**/*,\
  backend/src/main/java/ch/puzzle/pcts/model/**,\
  backend/src/main/java/ch/puzzle/pcts/dto/**,\
  backend/src/main/java/ch/puzzle/pcts/exception/**,\
  **/PctsApplication.java, **/SpringSecurityConfig.java,\
  frontend/src/app/**/*.spec.ts, frontend/src/app/**/*.scss,\
  frontend/src/app/**/*.html, frontend/src/app/app.config.ts,\
  frontend/src/app/app.routes.ts
sonar.sources=frontend/src/app, backend/src/main/java
sonar.tests=frontend/src/app, backend/src/test/java
sonar.test.inclusions = frontend/src/app/**/*.spec.ts, backend/src/test/java/**/*.java

sonar.cpd.exclusions=\
  backend/src/main/java/ch/puzzle/pcts/model/**,\

sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco-merged-test-coverage-report/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info