---
services:
  pcts-db:
    container_name: ptcs-dev-db
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: pcts
    ports:
      - 5432:5432
  pcts-app:
    container_name: pcts-app
    build: .
    ports:
      - 8080:8080
    depends_on:
      - pcts-db
