package ch.puzzle.pcts.model.error;

public enum ErrorKey {
    VALIDATION,
    VALIDATION_DOES_NOT_INCLUDE,
    INTERNAL,
    ID_IS_NOT_NULL,
    NOT_FOUND,
    ROLE_NAME_IS_NULL,
    ROLE_NAME_IS_EMPTY,
    EXPERIENCE_TYPE_NAME_IS_NULL,
    EXPERIENCE_TYPE_NAME_IS_EMPTY,
    EXPERIENCE_TYPE_POINTS_ARE_NULL,
    EXPERIENCE_TYPE_POINTS_ARE_NEGATIVE,
    CERTIFICATE_NAME_IS_NULL,
    CERTIFICATE_NAME_IS_EMPTY,
    CERTIFICATE_POINTS_ARE_NULL,
    CERTIFICATE_POINTS_ARE_NEGATIVE,
    CERTIFICATE_TYPE_IS_NULL,
    CERTIFICATE_TYPE_IS_NOT_NULL,
    CERTIFICATE_TYPE_IS_NOT_A_LEADERSHIP_EXPERIENCE,
    LEADERSHIP_EXPERIENCE_NAME_IS_NULL,
    LEADERSHIP_EXPERIENCE_NAME_IS_EMPTY,
    LEADERSHIP_EXPERIENCE_POINTS_ARE_NULL,
    LEADERSHIP_EXPERIENCE_POINTS_ARE_NEGATIVE
}
