package ch.puzzle.pcts.model.error;

public enum ErrorKey {
    VALIDATION,
    VALIDATION_DOES_NOT_INCLUDE,
    INTERNAL,
    ID_IS_NOT_NULL,
    NOT_FOUND,
    ROLE_NAME_IS_NULL,
    ROLE_NAME_IS_EMPTY,
    EXPERIENCE_TYPE_NAME_IS_NULL,
    EXPERIENCE_TYPE_NAME_IS_EMPTY,
    EXPERIENCE_TYPE_POINTS_ARE_NULL,
    EXPERIENCE_TYPE_POINTS_ARE_NEGATIVE,
}
