---
services:
  pcts-db:
    container_name: pcts-db
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: pcts
    ports:
      - "5432:5432"
    profiles: ['', backend, db, e2e]
  pcts-dev-backend:
    container_name: pcts-dev-backend
    build: ../backend
    ports:
      - "8080:8080"
    depends_on:
      - pcts-db
    environment:
      PCTS_SPRING_DATASOURCE_URL: pcts-db
      SPRING_PROFILE: dev
    profiles: ['', backend]

  pcts-e2e-backend:
    container_name: pcts-e2e-backend
    build: ../backend
    ports:
      - "8080:8080"
    depends_on:
      - pcts-db
    environment:
      SPRING_PROFILE: e2e-test
    profiles: [e2e]

  pcts-frontend:
    container_name: pcts-frontend
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
    ports:
      - "4200:80"
    profiles: ['', e2e]
