#!/bin/bash
git_base_path=$(git rev-parse --show-toplevel)

echo "**Changing into the root directory**"
cd "$git_base_path" || { echo "Could not find git_base_path. Aborting"; exit 1; }

echo "**Merging and running the docker-compose file**"
echo "----------------------------------------------------------------"
docker compose -f docker/docker-compose.yml -f docker/docker-compose.e2e.yml --profile backend up --build

echo "**Stopping the docker containers**"
trap 'docker compose -f docker/docker-compose.yml -f docker/docker-compose.e2e.yml down -v' EXIT
