#!/bin/bash
git_base_path=$(git rev-parse --show-toplevel)

echo "**Changing into the docker directory**"
cd "$git_base_path/docker" || { echo "Could not find git_base_path. Aborting"; exit 1; }

echo "**Running the e2e docker-compose stack**"
echo "----------------------------------------------------------------"
docker compose --profile e2e up --build

trap 'docker compose --profile e2e down -v' EXIT
