CREATE TABLE IF NOT EXISTS degree_type
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT NOT NULL,
    highly_relevant_points      NUMERIC NOT NULL,
    limited_relevant_points   NUMERIC NOT NULL,
    little_relevant_points   NUMERIC NOT NULL
);