CREATE TABLE IF NOT EXISTS role
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT NOT NULL,
    deleted_at      TIMESTAMP DEFAULT NULL,
    is_management   BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX role_name_undeleted_unique
    ON role (name)
    WHERE deleted_at IS NULL;