CREATE DOMAIN PCTS AS
    NUMERIC(6,2) NOT NULL CHECK (value >= 0);

CREATE TABLE IF NOT EXISTS experience_type
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                      TEXT    NOT NULL,
    highly_relevant_points    PCTS,
    limited_relevant_points   PCTS,
    little_relevant_points    PCTS
);