CREATE TABLE IF NOT EXISTS api_key
(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    hashed_key TEXT NOT NULL UNIQUE,
    last_used TIMESTAMP DEFAULT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE
);