CREATE TABLE IF NOT EXISTS member
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                TEXT,
    last_name           TEXT,
    abbreviation        TEXT,
    employment_state    TEXT,
    date_of_hire        DATE NOT NULL,
    is_admin            BOOLEAN,
    organisation_unit   BIGINT,
    deleted_at          TIMESTAMP DEFAULT NULL
);