CREATE TABLE IF NOT EXISTS certificate
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT,
    points          NUMERIC NOT NULL,
    is_deleted      BOOLEAN NOT NULL DEFAULT FALSE,
    comment         TEXT
)
