CREATE TABLE IF NOT EXISTS organisation_unit
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT NOT NULL UNIQUE,
    deleted_at      TIMESTAMP DEFAULT NULL
);