CREATE TABLE IF NOT EXISTS organisation_unit
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT NOT NULL,
    deleted_at      TIMESTAMP DEFAULT NULL
);

CREATE UNIQUE INDEX organisation_unit_name_undeleted_unique
    ON organisation_unit (name)
    WHERE deleted_at IS NULL;