CREATE TABLE IF NOT EXISTS certificate
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT,
    points          NUMERIC(6,2) NOT NULL CHECK (points >= 0),
    deleted_at      TIMESTAMP DEFAULT NULL,
    comment         TEXT
)
