CREATE TABLE IF NOT EXISTS certificate
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT,
    points          NUMERIC NOT NULL,
    deleted_at      TIMESTAMP DEFAULT NULL,
    comment         TEXT
)
