CREATE TABLE IF NOT EXISTS experience_type
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                      TEXT    NOT NULL,
    highly_relevant_points    DECIMAL NOT NULL CHECK ( highly_relevant_points = ROUND(highly_relevant_points, 2) ),
    limited_relevant_points   DECIMAL NOT NULL CHECK ( limited_relevant_points = ROUND(limited_relevant_points, 2) ),
    little_relevant_points    DECIMAL NOT NULL CHECK ( little_relevant_points = ROUND(little_relevant_points, 2) )
);