CREATE TABLE IF NOT EXISTS certificate
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT,
    points          PCTS,
    deleted_at      TIMESTAMP DEFAULT NULL,
    comment         TEXT
);

CREATE TABLE IF NOT EXISTS tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX tag_name_lower ON tag (LOWER(name));

CREATE TABLE certificate_tag
(
    certificate_id BIGINT NOT NULL,
    tag_id         BIGINT NOT NULL,
    PRIMARY KEY (certificate_id, tag_id),
    CONSTRAINT fk_certificate FOREIGN KEY (certificate_id)
        REFERENCES certificate (id),
    CONSTRAINT fk_tag FOREIGN KEY (tag_id)
        REFERENCES tag (id)
);
