springdoc.api-docs.enabled=true
springdoc.show-actuator=true
springdoc.swagger-ui.enabled=true

app.link-check.max-retries=0

app.member-sync.enabled=false

# Change the swagger-ui path to /api/ so it's accessible through the frontend
springdoc.api-docs.path=/api/v3/api-docs
springdoc.swagger-ui.path=/api/docs

# Authentication & JWT
pcts.security.authentication.display-name-claim=name
pcts.security.authorization.authorities-spel-expression=[pitc][roles]
pcts.security.authorization.admin-authorities=org_hr,org_gl