spring.application.name=PCTS

# Database
spring.datasource.url=jdbc:postgresql://${PCTS_SPRING_DATASOURCE_URL:localhost}:5432/pcts
spring.datasource.username=user
spring.datasource.password=pwd
spring.datasource.driver-class-name=org.postgresql.Driver

#Flyway
spring.flyway.locations=classpath:db/migration,classpath:db/e2e-data-migration
spring.flyway.schemas=public

# Swagger UI
springdoc.api-docs.enabled=true

# PTime Sync
app.member-sync.url=http://dummy-url.test
app.member-sync.enabled=true
app.member-sync.cron=0 0 3 * * ?
app.member-sync.username=
app.member-sync.password=

# Authentication & JWT
pcts.security.authorisation.admin-authorities=org_hr,org_gl
pcts.security.authentication.username-claim=name
pcts.security.authentication.email-claim=email
pcts.security.authorisation.authorities-spel-expression=[pitc][roles]