springdoc.api-docs.enabled=false
springdoc.show-actuator=true

# Keycloak config exposed to frontend
pcts.frontend.keycloak.url=https://sso.puzzle.ch/auth
pcts.frontend.keycloak.realm=pitc
pcts.frontend.keycloak.client-id=pitc_pcts_staging
