package ch.puzzle.pcts.dto.error;

public enum ErrorKey {
    VALIDATION,
    INTERNAL,
    NOT_FOUND,
    INVALID_ARGUMENT,

    ATTRIBUTE_NULL,
    ATTRIBUTE_NOT_NULL,
    ATTRIBUTE_NOT_NEGATIVE,
    ATTRIBUTE_NOT_BLANK,
    ATTRIBUTE_SIZE_BETWEEN,
    ATTRIBUTE_MIN_VALUE,
    ATTRIBUTE_MAX_VALUE,
    ATTRIBUTE_DATE_PAST,
    ATTRIBUTE_UNIQUE,
    ATTRIBUTE_NOT_BEFORE,
    ATTRIBUTE_NOT_EMAIL,
    ATTRIBUTE_WRONG_KIND,

    ERROR_MESSAGE_MISSING_KEY,
    ERROR_MESSAGE_INVALID_KEY,
    DUPLICATE_CALCULATION,
    ATTRIBUTE_DOES_NOT_MATCH,

    AUTHORIZATION_NOT_ALLOWED
}
