spring.application.name=pcts-migration
#spring.ai.openai.base-url= http://localhost:11434/v1
#spring.ai.openai.api-key=unused-ollama-key
#spring.ai.openai.chat.model=qwen3.5:9b

server.port=8081
spring.ai.openai.base-url=http://10.11.5.226:8000/v1
spring.ai.openai.api-key=unused-key
spring.ai.openai.chat.model=qwen-coder/bullpoint/Qwen3-Coder-Next-AWQ-4bit
spring.ai.openai.chat.stream-options.max-tokens=16384

logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.ai.chat.client=DEBUG
logging.level.org.springframework.ai.openai=DEBUG

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=22MB
backend.api.base-url=http://localhost:8080

spring.security.oauth2.client.registration.migration-client.provider=keycloak
spring.security.oauth2.client.registration.migration-client.client-id=migration-client
spring.security.oauth2.client.registration.migration-client.client-secret=DUBzSiX6c0FD3XIRRDLsK6TIBWz8ElqrwsH1g6zZM9GIr2qAM1XO2FvpV6vc7kqAU6rp0KtT1o6KEYgyEiHC4S
spring.security.oauth2.client.registration.migration-client.authorization-grant-type=client_credentials

spring.security.oauth2.client.provider.keycloak.token-uri=http://localhost:8544/realms/pitc/protocol/openid-connect/token