spring.application.name=PCTS-Migration

spring.ai.openai.chat.stream-options.max-tokens=16384


spring.security.oauth2.client.registration.migration-client.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.migration-client.provider=keycloak

logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.ai.chat.client=DEBUG
logging.level.org.springframework.ai.openai=DEBUG

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=22MB
