backend.api.base-url=https://pitc-pcts-stag.ocp-internal.cloudscale.puzzle.ch

spring.ai.openai.base-url=http://10.11.5.226:8000/v1
spring.ai.openai.api-key=unused-key
spring.ai.openai.chat.model=qwen-coder/bullpoint/Qwen3-Coder-Next-AWQ-4bit