---
name: 'Format'

on: [push]
jobs:

  backend:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK ${{vars.JAVA_VERSION}}
        uses: actions/setup-java@v5
        with:
          java-version: ${{vars.JAVA_VERSION}}
          distribution: 'adopt'
          server-id: github
          settings-path: ${{github.workspace}}

      - name: Format backend
        run: mvn spotless:check

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{vars.NODE_VERSION}}

      - name: Npm install
        run: npm ci

      - name: Format frontend
        run: npm run check-linting:all

  markdownlint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Ruby
        run: sudo apt-get install ruby-full

      - name: Install markdownlint
        run: sudo gem install mdl

      - name: Markdown linting
        run: find . -name "*.md" -not -path "./.github/ISSUE_TEMPLATE/*" | xargs mdl

  yamllint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install yamllint
        run: sudo apt-get install yamllint

      - name: yaml linting
        run: yamllint .
