---
name: on-push-to-main.yaml

on:
  push:
    branches:
      - main

jobs:
  format:
    uses: ./.github/workflows/reusable__format.yaml
    with:
      COMMIT_HASH: ${{ github.sha }}

  tests:
    uses: ./.github/workflows/reusable__tests.yaml
    with:
      COMMIT_HASH: ${{ github.sha }}

  e2e-tests:
    needs:
      - format
      - tests
    uses: ./.github/workflows/reusable__e2e-testing.yaml
    with:
      COMMIT_HASH: ${{ github.sha }}

  push-to-ghcr:
    needs: [e2e-tests, format, tests]
    uses: .github/workflows/reusable__upload-to-ghcr.yaml
