---
name: 'Tests'

on:
  push:

jobs:
  frontend-tests:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{vars.NODE_VERSION}}

      - name: Npm install
        run: npm ci

      - name: Run unit tests
        run: npm test
  backend-tests:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK ${{vars.JAVA_VERSION}}
        uses: actions/setup-java@v5
        with:
          java-version: ${{vars.JAVA_VERSION}}
          distribution: 'adopt'

      - name: Use Maven to run unit and integration tests
        run: mvn clean verify
